-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHUbfHDAPGt1RsxrG
OuKLGVBo3ZjwN/A+mrl0YbfbnDGgCgYIKoZIzj0DAQehRANCAARRYJeLz+zb0oTq
fCq1+bSLrXhzPFDjlyJSK1glScY8EGKV39hUoSvGfkPjtEEk+Feeyqg4ob2CD/z0
X09vn4+h
-----END PRIVATE KEY-----