workflows:
  ios-workflow:
    name: iOS Workflow
    max_build_duration: 60
    environment:
      vars:
        XCODE_PROJECT: "ios/App/App.xcodeproj"
        XCODE_SCHEME: "App"
        BUNDLE_ID: "com.iturut.voicenoteapp"
      node: 22
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.iturut.voicenoteapp
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Set Azure key in env
        script: |
          echo "REACT_APP_AZURE_SPEECH_KEY=$REACT_APP_AZURE_SPEECH_KEY" > .env
      - name: Build React app
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          echo $APP_STORE_CONNECT_PUBLISHER_PRIVATE_KEY | base64 -d > /tmp/auth_key.p8
          cat /tmp/auth_key.p8
          xcode-project use-profiles
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
      - name: Publish to TestFlight
        script: |
          app-store-connect publish \
            --path $(find build/ios/ipa -name "*.ipa") \
            --key-id "D2VV8X53U8" \
            --issuer-id "34fab976-700d-4dbf-a4fb-fb1ed884c32c" \
            --private-key @file:auth_key.p8 \
            --testflight
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - iturutapp@gmail.com